# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b3f49eb3132f4477c596ec7a928bb21008912e66c05bf5246b191d0b75c9a1376d645aad76ab739d983c0be65752f39f7d3f0c3effeda3e5c91ad378bc2877f2

test:
  secret_key_base: a056e4b3e1e5ea1f1db99b6a99fc5930cf9e3504650b3085c934111e1912c2e20a582372c976ec1b8cd11ecdfe0bc45cbaffbc8109b7e154518f2ab4e74a1983

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
